static const char CONTENT_HM_HTML[] PROGMEM = 
  "<html> <head> <title>OpenEvse WiFi</title> <style> body { font-family: 'Arial'; }\n"
  "        div.title {font-weight: 600; color: gray; text-align: right; }\n"
  "        div.value {font-size: 20px; font-weight: 600; text-align: left; }\n"
  "		div.valueMax {font-size: 12px; font-weight: 300; text-align: left; }\n"
  "		span.valueMax {font-size: 12px; font-weight: 300; text-align: left; }\n"
  "        div.titleR {font-size: 10px; font-weight: 100; color: gray; text-align: right; }\n"
  "        div.valueR {font-size: 10px; font-weight: 100; text-align: left; }\n"
  "        td { text-align: center; }\n"
  "        tr.border_top td { border-top: 1pt solid black; }\n"
  "        tr.border_bottom td { border-bottom: 1pt solid black; }\n"
  "        div.log {font-size: 15px; font-weight: 100; }\n"
  "\n"
  "        button{ margin-top: 10px; margin-bottom: 10px;} </style> <script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script> <script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script> <script type=\"text/javascript\"> var counter = 10;\n"
  "\n"
  "        function setValue(id, value) { var s = document.getElementById(id); s.innerText = value; }\n"
  "\n"
  "        $(document).ready(function () { getData(); getLog(); });\n"
  "\n"
  "        function refresh() {\n"
  "            counter--;\n"
  "\n"
  "            if (counter > 0) {\n"
  "                setValue('refresh', counter);\n"
  "            }\n"
  "            else {\n"
  "                counter = 10;\n"
  "                getData();\n"
  "            }\n"
  "        };\n"
  "\n"
  "        function getData() {\n"
  "            $.getJSON('/sensors',\n"
  "                function (data) {\n"
  "					setValue('t', data.t);\n"
  "                    setValue('e', data.e);\n"
  "					setValue('p', data.p);\n"
  "					setValue('c', data.c);\n"
  "					setValue('v', data.v);\n"
  "					setValue('t1', data.t1);\n"
  "					setValue('t1m', data.t1m);\n"
  "					setValue('t2', data.t2);\n"
  "                    setValue('t2m', data.t2m);\n"
  "                    setValue('t3', data.t3);\n"
  "					setValue('t3m', data.t3m);\n"
  "                    setValue('uptime', data.uptime);\n"
  "                    setValue('dateTime', data.time);\n"
  "                }\n"
  "            );\n"
  "        };\n"
  "\n"
  "		function getLog() {\n"
  "		    $.get('/log',\n"
  "			    function(data) {\n"
  "			        setValue('log', data);\n"
  "		        }\n"
  "		    );\n"
  "		};\n"
  "\n"
  "        setInterval(refresh, 1000);\n"
  "\n"
  "        google.load('visualization', '1.0', { 'packages': ['corechart'] });\n"
  "        google.setOnLoadCallback(drawChart);\n"
  "\n"
  "        function drawChart() {\n"
  "\n"
  "            $.ajax({\n"
  "                type: \"GET\",\n"
  "                url: '/sarray',\n"
  "                success: function (receivedData) {\n"
  "\n"
  "					var interval = 30000;\n"
  "                    var today = new Date();\n"
  "                    today = new Date(today.getTime() - receivedData.svalues.length * interval);\n"
  "\n"
  "                    var data = new window.google.visualization.DataTable();\n"
  "                    data.addColumn('datetime', 'Date');\n"
  "                    data.addColumn('number', 'T1');\n"
  "                    \n"
  "                    for (var i = 0; i < receivedData.svalues.length; i++) {\n"
  "                        data.addRow([today, receivedData.svalues[i]]);\n"
  "                        today = new Date(today.getTime() + interval);\n"
  "                    }\n"
  "\n"
  "\n"
  "                    var width = 400;\n"
  "                    var height = 300;\n"
  "\n"
  "                    var options = {\n"
  "                        'width': width,\n"
  "                        'height': height,\n"
  "                        legend: 'none',\n"
  "                        hAxis: { format: 'HH:mm:ss' },\n"
  "                        'chartArea': {\n"
  "                            top: 10,\n"
  "                            left: 35,\n"
  "                            width: width - 35,\n"
  "                            height: height - 30\n"
  "                        },\n"
  "                        explorer: {\n"
  "                            actions: ['dragToZoom', 'rightClickToReset'],\n"
  "                            maxZoomIn: 0.01\n"
  "                        }\n"
  "                    };\n"
  "\n"
  "                    var formatter = new window.google.visualization.DateFormat({ pattern: 'HH:mm:ss' });\n"
  "                    formatter.format(data, 0);\n"
  "\n"
  "                    // Instantiate and draw our chart, passing in some options.\n"
  "                    var chart = new window.google.visualization.LineChart(document.getElementById('chart_div'));\n"
  "                    chart.draw(data, options);\n"
  "                },\n"
  "                dataType: \"json\",\n"
  "                traditional: true\n"
  "\n"
  "             });\n"
  "        } </script> </head> <body> <table style=\"border-collapse: collapse; border-spacing: 0;\"> <tr><td><div class=\"title\">Energy total:</div></td><td><div id=\"t\" class=\"value\">000</div></td></tr> <tr><td><div class=\"title\">Energy:</div></td><td><div id=\"e\" class=\"value\">000</div></td></tr> <tr><td><div class=\"title\">Power:</div></td><td><div id=\"p\" class=\"value\">000</div></td></tr> <tr><td><div class=\"title\">Voltage:</div></td><td><div id=\"v\" class=\"value\">000</div></td></tr> <tr><td><div class=\"title\">Current:</div></td><td><div id=\"c\" class=\"value\">000</div></td></tr> <tr><td><div class=\"title\">Temperature in:</div></td><td><div id=\"t1\" class=\"value\">000</div></td> <td><div class=\"valueMax\"><span class=\"valueMax\">(</span><span id=\"t1m\">000</span><span class=\"valueMax\">)</span></div></td></tr> <tr><td><div class=\"title\">Temperature in2:</div></td><td><div id=\"t2\" class=\"value\">000</div></td> <td><div class=\"valueMax\"><span class=\"valueMax\">(</span><span id=\"t2m\">000</span><span class=\"valueMax\">)</span></div></td></tr> <tr><td><div class=\"title\">Temperature out:</div></td><td><div id=\"t3\" class=\"value\">000</div></td> <td><div class=\"valueMax\"><span class=\"valueMax\">(</span><span id=\"t3m\">000</span><span class=\"valueMax\">)</span></div></td></tr> <tr class=\"border_top\"><td><div class=\"title\">UpTime:</div></td><td colspan=\"2\"><div id=\"uptime\" class=\"value\">0.00:00:00</div></td></tr> <tr class=\"border_bottom\"><td><div class=\"title\">Time:</div></td><td colspan=\"2\"><div id=\"dateTime\" class=\"value\" style=\"text-align: left\"></div></td></tr> <tr><td><div class=\"titleR\">refresh in:</div></td><td colspan=\"2\"><div id=\"refresh\" class=\"valueR\">9</div></td></tr> </table> <div id=\"chart_div\" style=\"width:400px; height:300px\"></div> <button onclick=\"drawChart();\">Refresh chart</button> <button onclick=\"getLog();\">Refresh log</button> <div class=\"log\" id=\"log\"></div> </body> </html>\n";
